---
name: Test workflow
on:
  push:
  workflow_dispatch:

jobs:
  peepoo:
    name: "PeePoo"
    # runs-on: debian-latest
    runs-on: self-hosted
    steps:
      - name: Run test command
        run: echo "hello world"
      - name: Echo test var
        run: echo "${{ vars.test_var }}"
      - name: Echo test secret
        run: echo "${{ secrets.test_secret }}"
